services:
  - type: web
    name: cpss-app
    runtime: node
    rootDir: cpssapp
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_PASSWORD
        value: changez-moi-admin
      - key: VIEWER_PASSWORD
        value: changez-moi-bureau
      - key: SESSION_SECRET
        generateValue: true
